version: '3.7'

networks:
  backend:
    driver: bridge

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "PortfolioAPIPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      backend:
        aliases:
          - dbcontainer
  
      
        

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      backend:
