name: Build - Test

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.203

      - name: Restore dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore back-end/PortfolioAPI/PortfolioAPI/PortfolioAPI.csproj

      - name: Build Test Project
        run: dotnet build --configuration Debug --no-restore back-end/PortfolioAPI/PortfolioAPI.Tests/PortfolioAPI.Tests.csproj

      - name: Test
        run: dotnet test --no-build --verbosity normal back-end/PortfolioAPI/PortfolioAPI.Tests/PortfolioAPI.Tests.csproj
